#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1096436735                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://itunes.apple.com/us/app/cinema-time/id1096436735                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : http://maximilianlitteral.com/MovieTime/PressKit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Cinema Time                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : "\"There's no better time to find the right movie tracking app for you, and Cinema Time is one of the best.\" - Ryan Christoffel from MacStories"

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Maximilian Litteral
your_link                                 : http://maximilianlitteral.com
your_city                                 : Massachusetts
email_address                             : support@cinematime.app
facebook_username                         :
instagram_username                        :
twitter_username                          : Movie_App
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Trakt.tv Sync
    description                           : Sign in to your Trakt.tv account to see your history, watchlist, collection, and custom lists
    fontawesome_icon_name                 : sync-alt

  - title                                 : Details at a glance
    description                           : Overview, release date, Rotten Tomatoes & IMDb scores, cast, and more
    fontawesome_icon_name                 : info-circle

  - title                                 : Track how many movies you see
    description                           : View various statistics about your movie watching habits such as time spent watching movies, number of movies seen, and movie history.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Social Links
    description                           : View movie info from Trakt, TheMovieDB, and IMDb
    fontawesome_icon_name                 : link

  - title                                 : Multiple languages supported
    description                           : English, Spanish, Italian, German, Japanese, and more.
    fontawesome_icon_name                 : language

  - title                                 : Accessibility Support
    description                           : VoiceOver, Dynamic text, and more!
    fontawesome_icon_name                 : universal-access

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#343434"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FC1745"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

include:
  - .well-known

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
